### ISSUE TITLE
olleH dlroW

### ISSUE THREAD

**Issue by beachwalker** [tintoy/rx-akkadotnet#1]
I think your Example from the start page produces   olleH dlroW and not dlroW olleH. Only the message is reversed (single OnNext argument) and not the whole message list is inverted. Or did I missed something in the code? Cause you didn't add a special threading scheduler for rx pat the order of messages should be delivered as added with OnNext calls. Didn't tried, just reading your code sample... ;-)

**Comment by tintoy** [comment]
Hi :)

Sorry, apparently I've spent too much time playing with more recent versions of the dotnet SDK, so I can't build / run this right now. It's been a while, so I don't remember what the expected behaviour is, but at first glance it _does_ look like you're right!

I'll try to get it building with a more recent version of the SDK and build a test-harness to try it out.

**Comment by tintoy** [comment]
(either way, thanks for taking the time to report it!)

**Comment by tintoy** [comment]
Yep you're right about the order - don't know how I missed that.

I'll update the README. That `ToSubject` extension method doesn't actually exist BTW, I hadn't got around to building it when I forgot about this project.

Maybe this is something worth working on over the holiday break :)

**Comment by tintoy** [comment]
I've closed this issue, but only because I'm tracking the work in #2.

Thanks again for the catch.
